### ISSUE TITLE
Course card on homepage

### ISSUE THREAD

**Issue by cyrildewit** [LeerPlatform/main-application#8]
## Todo

* [x] When hovering over the card, the image should fade into a darker color
* [x] When the description excerpt is longer than xxx it should be shortened.
* [x] Style authors when there are more than one
* [x] Style tags for multiple ones (fix not moving to next line)
* [x] Show real course image
* [ ] Make authors name linked to there page
* [ ] Link tag to catalog page with filter to the tag
